kind: ConfigMap
apiVersion: v1
metadata:
  name: jerry-ui5-kyma
  labels:
    app: jerry-ui5-kyma
data:
  config.json: |-
    {
      "API_URL": "https://wugui5.c-79cbe95.kyma.shoot.live.k8s-hana.ondemand.com/"
    }