apiVersion: apps/v1
kind: Deployment
metadata:
  name: wug-order-kyma-1
  labels:
    app: wug-order-kyma-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wug-order-kyma-1
  template:
    metadata:
      labels:
        app: wug-order-kyma-1
    spec:
      containers:
        - name: wug-order-kyma-1
          image: acobpm/wug-ui5-first
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: wug-order-kyma-1
---
apiVersion: v1
kind: Service
metadata:
  name: wug-order-kyma-1
  labels:
    app: wug-order-kyma-1
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: wug-order-kyma-1