apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-ui5-kyma
  labels:
    app: jerry-ui5-kyma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerry-ui5-kyma
  template:
    metadata:
      labels:
        app: jerry-ui5-kyma
    spec:
      containers:
        - name: jerry-ui5-kyma
          image: i042416/ui5-kyma
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: jerry-ui5-kyma
---
apiVersion: v1
kind: Service
metadata:
  name: jerry-ui5-kyma
  labels:
    app: jerry-ui5-kyma
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: jerry-ui5-kyma